//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.SQL.ProjectTracker.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dTask
    {
        public int Id { get; set; }
        public int dProjectId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual dProject ProjectID { get; set; }
    }
}
